config/routes.rb
Rails.application.routes.draw do
  # get 'boarding/index'


  resources :boarding do
    post 'seteditingsite'
    get 'search'
    resources :category do
      resources :site
      get 'movecategory'
    end
  end

  resources :category do
    resources :site do
      get 'movesite',via: :post
    end
    get 'movecategory'
  end

  root 'boarding#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :categories,dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :board
  has_many :sites,dependent: :destroy
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boarding_controller.rb
class BoardingController < ApplicationController

  http_basic_authenticate_with name: "yuanchenhao",password: "",only: [:new,:create]

  def index
    redirect_to boarding_path(:id=>1)
  end

  def new
    @newboard = Board.new()
    create
  end

  def create
    @newboard = Board.new()

    @newcategory = Category.new()
    @newboard.categories.push(@newcategory)

    if @newboard.save
      redirect_to action: "show", id: @newboard[:id]
    else
      redirect_to root_path
    end
  end

  def show
    @boardindex = params[:id].to_i
    if @boardindex == 0
      @boardindex = 1
    end
    @board = Board.find(@boardindex)
    @boardtotalnum = Board.count

    @site = Site.new()

  end

  def search

    @search_word = params[:q]

    @boardindex = params[:boarding_id].to_i

    @results = Array.new
    @board = Board.find(@boardindex)
    @board.categories.each do |category|
        category.sites.each do |site|
          if (site.title.include? @search_word) || (site.url.include? @search_word)
            @results.push(site)
          end
        end
    end

    @googletext = ',"action": {"url": "https://www.google.com/#q='+@search_word + '"'+ ', "text": "搜索 '+@search_word + '"'+ '}'

    @resultjson = '{"success": true,"results":'+ @results.to_json(:except => [:category_id,:created_at,:updated_at,:id]) + @googletext + '}'

    render plain: @resultjson

    # render :json => @results,content_type: 'application/json'
    # render :json => @board,content_type: 'application/json', :include => [:categories => { :include => [:sites => {}] }],:except => [:title,:created_at,:updated_at,:id]
    # render json: @board ,content_type: 'application/json'
  end

  # def newcategory (boardindex)
  #   @board = Board.find(boardindex)
  #   @newcategory = Category.new()
  #   @board.categories.push(@newcategory)
  # end

  # def seteditingsite
  #   @site = Category.find(params[:categoryindex]).sites.new()
  # end
  # helper_method :seteditingsite

  private

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  http_basic_authenticate_with name: "yuanchenhao",password: "",except: [:show]

  def new
    create
  end
  def create
    @board = Board.find(params[:boarding_id])
    @category = @board.categories.create()
    redirect_to boarding_path(@board)
  end

  def show

  end

  def destroy
    @board = Board.find(params[:boarding_id])
    if @board.valid?
      @category = @board.categories.find(params[:id])
      @category.destroy
      redirect_to boarding_path(@board)
    else

    end

  end

  def update
    @category = Category.find(params[:id])
    @board = @category.board
    if @category.update(params.require(:category).permit(:title))
      redirect_to boarding_path(@board)
    else
      redirect_to boarding_path(@board)
    end
  end

  def movecategory

    @boardingid = params[:boarding_id]
    @categoryid = params[:category_id]
    @directionnext = params[:directionNext]

    @category = Category.find(@categoryid)
    @category_to_swap
    @boardto = Board.find(@boardingid)
    @board_categories = @boardto.categories
    @category_index_in_categories = @boardto.categories.find_index(@category)

    if @directionnext == 'false'
        if @category_index_in_categories == 0
        else
          @category_to_swap = @board_categories[@category_index_in_categories - 1]

          @category.title,@category_to_swap.title = @category_to_swap.title,@category.title
          @category.sites,@category_to_swap.sites = @category_to_swap.sites,@category.sites

          @category.save
          @category_to_swap.save

        end
    else
        if @category_index_in_categories == @board_categories.count - 1
        else
          @category_to_swap = @board_categories[@category_index_in_categories + 1]

          @category.title,@category_to_swap.title = @category_to_swap.title,@category.title
          @category.sites,@category_to_swap.sites = @category_to_swap.sites,@category.sites

          @category.save
          @category_to_swap.save
        end
    end

    redirect_to boarding_path(params[:boarding_id])
  end

  private


end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  http_basic_authenticate_with name: "yuanchenhao",password: "",except: [:show]

  def new
    @site = Site.new()
  end
  def create
    @category = Category.find(params[:category_id])
    @site = @category.sites.create(params.require(:site).permit(:url, :title))
    redirect_to boarding_path(@category.board)
  end

  def show

  end

  def destroy
    @category = Category.find(params[:category_id])
    @site = Site.find(params[:site_id])
    @site.destroy
    redirect_to boarding_path(@category.board)
  end

  def movesite

    @siteid = params[:site_id]
    @boardingid = params[:boarding_id]
    @categoryid = params[:category_id]
    @directionnext = params[:directionNext]

    @site_from = Site.find(@siteid)
    @site_to
    @category = Category.find(@categoryid)
    @sites_array = @category.sites

    @site_index = @sites_array.find_index(@site_from)

    if @directionnext == 'false'
      if @site_index == 0
      else
        @site_to = @sites_array[@site_index - 1]

        @site_from.title,@site_to.title = @site_to.title,@site_from.title
        @site_from.url,@site_to.url = @site_to.url,@site_from.url

        @site_from.save
        @site_to.save

      end
    else
      if @site_index == @sites_array.count - 1
      else
        @site_to = @sites_array[@site_index + 1]

        @site_from.title,@site_to.title = @site_to.title,@site_from.title
        @site_from.url,@site_to.url = @site_to.url,@site_from.url

        @site_from.save
        @site_to.save
      end
    end


    redirect_to boarding_path(params[:boarding_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boarding_helper.rb
module BoardingHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/boarding/_background.erb
<div id="particles" style="position:fixed;
    top:0;
    left:0;
    width:100%;
    height:100%;
    z-index:-1;">
  <div class="ui" style="position: fixed;bottom: 0.5em;right: 0.5em">
    <div id="page_load_time" class="ui text" style="text-align: center; font-size:0.5em;color: darkgray;"></div>
  </div>
</div>
<script>
  $('#particles').particleground({
    dotColor: '#ccccff',
    lineColor: '#f2e6ff',
    parallax:false,
    proximity:100,
    particleRadius:5
  });
</script>

app/views/boarding/_board.erb
<script src="https://unpkg.com/masonry-layout@4.1/dist/masonry.pkgd.min.js"></script>

<div class="ui" style="padding-top: 5em;padding-bottom: 2em;">
  <div id="boardgrid" class="ui grid doubling six column" style="margin: 0 auto;">
    <% @board.categories.all.each_with_index do |category,index| %>
        <div class="ui boardgridcell column">
          <%= render :partial => "category/categorycard", :locals => {:category => category,:categoryindex => index,:boardindex => @boardindex,:board => @board} %>
        </div>
    <% end %>
    <script>
      $('.categorycard.dropdown')
          .dropdown({
            // you can use any ui transition
            transition: 'fade',
            action: function() {
              // nothing built in occurs
            },
          })
      ;

      $('.sitecell .dropdown')
          .dropdown({
            action: 'hide'
          })
      ;
      $('#boardgrid').masonry({
        // options...
        itemSelector: '.ui.boardgridcell.column',
        gutter: 0,
      });
    </script>
  </div>
</div>

<script type="text/javascript">
  function toggleEditCategoryName(event,contentindex)
  {
    if (contentindex == 0)
    {
      $(event.target).closest('.content').next().transition('slide down', 200, function() {
        $('#boardgrid').masonry('layout');
      })
      ;
    }
    if (contentindex == 1)
    {
      $(event.target).closest('.content').transition('slide down', 200, function() {
        $('#boardgrid').masonry('layout');
      })
      ;
    }
  }
  function toggleAddSite(event,contentindex)
  {
    if (contentindex == 0)
    {
      $(event.target).closest('.content').next().next().next().transition('slide down', 200, function() {
        $('#boardgrid').masonry('layout');
      })
      ;
    }
    if (contentindex == 1)
    {
      $(event.target).closest('.content').transition('slide down', 200, function() {
        $('#boardgrid').masonry('layout');
      })
      ;
    }
  }
</script>

app/views/boarding/_misc.erb
<script>
  window.onload = function () {
    var loadTime = window.performance.timing.domContentLoadedEventEnd-window.performance.timing.navigationStart;
    console.log('Page load time is '+ loadTime);
    document.getElementById('page_load_time').innerHTML = ' '+ loadTime + ' ms';
  }
</script>

app/views/boarding/_searchbar.erb
<div class="ui menu large borderless top fixed">
  <div class="item" style="padding: 0.1em"></div>


  <div id="dropdownbutton" class="ui floating dropdown browse item button teal" >
    <%= image_tag("icon.png", class:"ui mini image")%>
    <div class="dropdown icon"></div>
  </div>
  <div id="dropdownbuttonpopup" class="ui popup bottom left transition hidden" style="min-width: 20em;padding: 0.5em">

    <div class="item">
      <h5 class="ui violet header" style="margin: 0em">
        Switch Board
      </h5>
      <div class="ui basic icon buttons fluid">
        <% if @boardindex <= 1 %>
        <% else %>
            <%= link_to boarding_path(:id => @boardindex - 1) ,class: "ui button" do %>
              <i class="chevron left icon"></i>
            <% end %>
        <% end %>
        <%= link_to boarding_path(:id => @boardindex) ,class: "ui button" do %>
            第 <%= @boardindex %> 页
        <% end %>
        <% if @boardindex >= @boardtotalnum %>
        <% else %>
            <%= link_to boarding_path(:id => @boardindex + 1) ,class: "ui button" do %>
                <i class="chevron right icon"></i>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="item">
      <h5 class="ui violet header" style="margin: 0em">
        Categories Control
      </h5>
      <div class="ui one basic icon buttons fluid">
        <%= link_to new_boarding_category_path(:boarding_id => @boardindex) ,class: "ui button" do %>
            <i class="add circle icon icon"></i>
        <% end %>
      </div>
    </div>

  </div>

  <div class="ui item right">
    <div class="ui category search right aligned">

      <div class="ui mini icon input">
          <input id="searcgbarinput" class="prompt" type="text" placeholder="搜索网站..." autofocus="">
          <i class="search icon"></i>
      </div>

      </div>
      <div id="searchresultsonbar" class="results"></div>
    </div>
  </div>
</div>

<script>
  $('.teal.button')
      .popup({
        inline   : true,
        hoverable: true,
        position : 'bottom left',
        delay: {
          show: 0,
          hide: 400
        }
      })
  ;

  $('.ui.search.category')
      .search({
        apiSettings:
        {
          url: document.URL.replace(/\/$/, "")+'/search?q={query}',
          onResponse : function(theresponse) {
            // here you modify theresponse object,
            // then you return the modified version.
            console.log(theresponse);
//            alert(theresponse);
          }
        },
        fields:
        {
          title     : 'title',
          url       : 'url'
        },
        searchDelay:200,
//        verbose:true,
//        debug:true,
//        cache:false,
        error : {
          source      : 'Cannot search. No source used, and Semantic API module was not included',
          noResults   : '没有网站',
          logging     : 'Error in debug logging, exiting.',
          noTemplate  : 'A valid template name was not specified.',
          serverError : 'There was an issue with querying the server.',
          maxResults  : 'Results must be an array to use maxResults setting',
          method      : 'The method you called is not defined.'
        },
        onResults : function(theresponse) {
          // here you modify theresponse object,
          // then you return the modified version.
          console.log(theresponse);
        },
        onResultsOpen : function() {
          $('#searchresultsonbar').css('width','10em');
        },
        onSelect : function(result, response)
        {
          document.getElementById('searchbarinput').value = "";
          var win = window.open(result.url, '_blank');
          win.focus();
          return false;
        }
      })
  ;

  $('#searchbarinput').keypress(function()
  {
    if (event.which == 13 || event.keyCode == 13)
    {
      var googlelink = 'https://www.google.com/#q=' + document.getElementById('searchbarinput').value;
      var win = window.open(googlelink, '_system');
      win.focus();
    }
  });

</script>
<script type="text/javascript">
  window.onload = function(){
    var text_input = document.getElementById ('searchbarinput');
    text_input.focus ();
    text_input.select ();
  }
</script>

app/views/boarding/index.html.erb
<% if @board.nil? %>
    redirect_to boarding_url
<% end %>

app/views/boarding/show.html.erb
<%= render 'boarding/searchbar' %>
<%= render 'boarding/board' %>
<%= render 'boarding/misc' %>
<%= render 'boarding/background' %>
<script>
  $( document ).ready(function()
  {
    if ('-webkit-backdrop-filter' in document.body.style)
    {
      $('.ui.card.fluid').css("-webkit-backdrop-filter", "blur(3px)");
      $('.ui.card.fluid').css("background", "rgba(255,255,255,0.1)");
      $('.ui.menu.large.borderless.top.fixed').css("-webkit-backdrop-filter", "blur(3px)");
      $('.ui.menu.large.borderless.top.fixed').css("background", "rgba(255,255,255,0.1)");
    }
  });
</script>
<% if @board.nil? %>
    redirect_to boarding_url
<% end %>

app/views/category/_categorycard.erb
<div class="ui card fluid">
  <div class="content">
    <div class="ui right floated configure violet icon">
     
    </div>
    <div class="ui right floated configure violet icon">
      <div class="categorycard ui pointing top right dropdown">
        <i class="wrench icon" style="color: grey"></i>
        <div class="vertical left menu">
          <div class="header">
            Add
          </div>

          <div class="item" onclick="toggleAddSite(event,0)">
            Add Website
          </div>
          <div class="divider"></div>
          <% if false %>
          <div class="header">
            Move
          </div>
          <%= link_to boarding_category_movecategory_path(:boarding_id => boardindex, :category_id => category.attributes['id'],:directionNext => 'false' ),
                        class: "item" do %>
              Move Back
          <% end %>
          <%= link_to boarding_category_movecategory_path(:boarding_id => boardindex, :category_id => category.attributes['id'],:directionNext => 'true' ),
                      class: "item" do %>
              Move Next
          <% end %>
          <div class="divider"></div>
          <% end %>
          <div class="header">
            Edit
          </div>
          <div class="item" onclick="toggleEditCategoryName(event,0)">
            Change Name
          </div>
          <%= link_to boarding_category_url(:boarding_id => boardindex, :id => category.attributes['id']),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } ,class: "item" do %>
              Delete
          <% end %>
        </div>
      </div>

    </div>

    <div class="header" style="color: #3A009E;"><%= category.title %></div>
  </div>
  <div class="content transition hidden">

    <%= form_for category do |f| %>
        <div class="ui form">
          <%= f.text_area :title,:class => "field",:style=>"resize:none; outline: none;",:rows => 1 do%>
              <input type="text" placeholder="Category Name">
          <% end %>
          <div class="ui buttons fluid">
            <div class="ui red basic button" onclick="toggleEditCategoryName(event,1)">取消</div>
            <%= button_tag(type: "submit", class: "ui green basic button") do %>
                确定
            <% end %>
          </div>
        </div>
    <% end %>
  </div>

  <div class="content">
    <div class="ui list selection">
      <% category.sites.all.each_with_index do |site,index| %>
          <div class="item">
            <div class="ui sitecell right floated ">
              <div class="ui dropdown pointing right">
                <i class="ellipsis horizontal icon"></i>
                <div class="menu">
                  <%= link_to category_site_movesite_path(:site_id => site.attributes['id'], :category_id => category.attributes['id'],:boarding_id => @board.attributes['id'],:directionNext => 'false',:method=>:post),
                              class: "item" do %>
                      <i class="angle up icon"></i>
                      Move Up
                  <% end %>
                  <%= link_to category_site_movesite_path(:site_id => site.attributes['id'], :category_id => category.attributes['id'],:boarding_id => @board.attributes['id'],:directionNext => 'true',:method=>:post),
                              class: "item" do %>
                      <i class="angle down icon"></i>
                      Move Down
                  <% end %>
                  <%= link_to boarding_category_site_path(:category_id => category.attributes['id'],:site_id => site.attributes['id'],:id => site.attributes['id'],:boarding_id => @board.attributes['id']),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } ,class: "item" do %>
                      <i class="trash outline icon"></i>
                      Delete
                  <% end %>
                </div>
              </div>
            </div>
            <div class="content">
              <%= link_to site.url,target:"_blank",rel: "nofollow",style:"color:#5F6873"  do %>
                  <%= site.title %>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>

  </div>

  <div class="content transition hidden">

    <%= form_for [category,@site],url: category_site_index_path(:category_id=>category.attributes['id']) do |f| %>
        <div class="ui form">
          <%= f.text_area :title,:class => "field",:style=>"resize:none; outline: none;",:rows => 1 do%>
              <input type="text" placeholder="Category Name">
          <% end %>
          <%= f.text_area :url,:class => "field",:style=>"resize:none; outline: none;",:rows => 1 do%>
              <input type="text" placeholder="Category Name">
          <% end %>
          <div class="ui buttons fluid">
            <div class="ui red basic button" onclick="toggleAddSite(event,1)">取消</div>
            <%= button_tag(type: "submit", class: "ui green basic button") do %>
                确定
            <% end %>
          </div>
        </div>
    <% end %>
  </div>

</div>

app/views/category/movecategory.html.erb
<%= debug(@categoryindexincategories)%>
<%= debug(@boardto)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pin</title>

    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <%= favicon_link_tag 'favicon.ico' %>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name = "viewport" content = "user-scalable=no, width=device-width">
    <link rel="apple-touch-icon"
          sizes="144x144"
          href=<%= image_path("apple-touch-icon-144x144.png") %>>
    <meta name="apple-mobile-web-app-title" content="Fragment">

    <%= csrf_meta_tags %>


    <%= javascript_include_tag 'jquery-2.2.3.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'semantic_components/popup.min', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'jquery.particleground.min', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>